### ISSUE TITLE
Typo - you're to your

### ISSUE THREAD

**Issue by jessluo8** [joshjluo/personal-finance-guide#28]
Credit > Why should you use a credit card? > Credit Score > How does it impact you?
![image](https://user-images.githubusercontent.com/45980348/114324796-c7835180-9af1-11eb-9524-49446de9c431.png)

**Comment by NovusEdge** [comment]
I would like to resolve this if no one's assigned

**Comment by joshjluo** [comment]
Looks like @thehannankhan already made a PR for the fixes. Thanks for your interest though! 😄 I'm sure there will be plenty of other typos and bugs to be fixed in the future
